biothings/discovery-app

discovery/web/handlers.py, discovery/web/siteconfig/default.py, discovery/web/siteconfig/n3c.py, discovery/web/siteconfig/niaid.py, discovery/web/siteconfig/outbreak.py, discovery/web/templates/metadata-page.html
Readable labels are handled in priority by (1) mappings in configs, (2) snake_case, (3) camelCase and capitalizes individual words.
=> Readable labels in dataset pages

discovery/web/templates/schema-viewer.html
Schema viewer: Display and sort validation props by required, recommended and optional specification.
=> feat: :sparkles: Update schema viewer

discovery/web/templates/metadata-page.html
=> feat: :sparkles: markdown rendered in metadata description field

discovery/web/handlers.py, discovery/web/templates/faq-multi.html, discovery/web/templates/flowchart.html, discovery/web/templates/footer.html, discovery/web/templates/json-schema-viewer.html, discovery/web/templates/metadata-guide-new.html, discovery/web/templates/metadata-page.html, discovery/web/templates/metadata-registry.html, discovery/web/templates/portal.html, discovery/web/templates/portals.html, discovery/web/templates/schema-editor.html, static/img/faq-01.svg
N3C PPRL FAQ page added. FAQ page refactor.
=> feat: :sparkles: dedicated FAQ pages per portal, N3C added

discovery/web/templates/dashboard.html, discovery/web/templates/faq-multi.html, discovery/web/templates/metadata-registry.html, discovery/web/templates/schema-editor.html
remove some PPRL FAQ's, registered items overflow to scroll, update schema `ns` param for **bioschemas** added, FAQ PPRL direct links added based on metadata name, FAQ section links added.
=> fix: various small fixes

templates/schema-viewer.html
Show term examples and tip hover full info below test query term lookup button.
=> feat: :sparkles: ontology term examples

templates/dashboard.html, templates/registry.html
Paginate dataset hits public/private
=> fix: :hammer: paginate dashboard datasets

discovery/handlers/templates.py, discovery/siteconfig/default.py, discovery/siteconfig/n3c.py, discovery/siteconfig/niaid.py, discovery/siteconfig/outbreak.py, templates/dashboard.html, templates/guides.html, templates/metadata-guide-new.html, templates/metadata-registry.html, templates/portal.html
Updated NIAID portal, registry, CT guide.  
Bulk registration new features:
warning for null values and quick fix.
warning for already registered items and skip.
warning for missing values required and optional.
ability to add new fields or edit existing.
improved error reporting/layout.
=> feat: :sparkles: NIAID CompTool guide, improved bulk registration

templates/metadata-guide-new.html
=> feat: :sparkles: bulk report

templates/dashboard.html
=> feat: :sparkles: dashboard dataset search

templates/metadata-registry.html
=> feat: :sparkles: download metadata from registry, group pagination

templates/metadata-registry.html, templates/schema-viewer.html
=> fix: :hammer: csv export, bug fix property view

templates/header.html, templates/schema-editor.html
=> fix :hammer: editor descrition option added

templates/metadata-guide-new.html, templates/schema-editor.html
You can manage (save, load and delete) multiple progress files and pick up where you left off.
=> feat: :sparkles: save and load progress

templates/schema-editor.html
=> feat: :sparkles: optional validation type vs profile

scripts/metadata_admin.py
Admin module to transfer ownership of metadata, delete, update, and bulk update metadata.
=> feat: :sparkles: metadata admin module

templates/schema-editor.html
=> feat: :sparkles: edit descriptions and cardinality - editor

templates/schema-editor.html
=> fix: :hammer: preload existing cardinality

templates/portal.html, templates/portals.html, templates/schema-viewer.html
NDE special descriptions, viewer descriptions, misc. layout updates/fixes.
=> dev: :hammer: nde portal updates, viewer descriptions

config.py, discovery/handlers/api/__init__.py, discovery/handlers/api/validate.py
=> Add metadata validation endpoint

nuxt-app/components/SchemaRegistryItem.vue, nuxt-app/pages/dataset/index.vue
Always use curie when using the /registry endpoint 
Fix bug where checking an undefined property causes a bug on the metadata registry
=> fix: :hammer: registry url format, filters on meta registry

nuxt-app/components/guide/InputBox.vue, nuxt-app/pages/guide/Guide.vue
add missing `moment.js` imports causing date parsing issues.
=> fix: :hammer: add missing imports

nuxt-app/assets/css/styles.css, nuxt-app/components/JS_DefinitionBox.vue, nuxt-app/components/QueryBox.vue, nuxt-app/components/global/AnyOf.vue, nuxt-app/components/global/OneOf.vue, nuxt-app/components/global/TypeSelector.vue, nuxt-app/components/guide/InputBox.vue, nuxt-app/components/guide/InputPreview.vue, nuxt-app/components/guide/Vocabulary.vue, nuxt-app/pages/guide/Guide.vue, nuxt-app/store/index.js, nuxt-app/store/modules/auth.js, nuxt-app/store/modules/guide.js
Includes fixes to: 
https://github.com/biothings/discovery-app/issues/245
Features:
Adds NDE portal and guides
=> Editor fixes

scripts/fix_niaid_datasets.py
Adds @context for NIAID datasets
Fixes outdates names or adds missing prefixes
=> Fix datasets with missing context or outdated names

nuxt-app/components/guide/JSONItem.vue, nuxt-app/pages/guide/Guide.vue, nuxt-app/plugins/fontawesome.js, nuxt-app/store/modules/guide.js
=> fix: :hammer: add context, fix edit tool

nuxt-app/assets/css/styles.css, nuxt-app/components/Nav.vue, nuxt-app/components/guide/JSONItem.vue, nuxt-app/pages/metadata-playground/index.vue, nuxt-app/pages/portal/[portal_name]/index.vue, nuxt-app/store/modules/guide.js
Adds:
- improved layout
- validate against schema (local) (provides full paths to issues)
- validate against schema (API) (provides a more readable result but simpler)
- improved preview modal with collapsible brackets
- better font size
- ordered metadata keys
Also adds new Metadata Playground options on the navigation menu
=> fix: :hammer: add validation options, issue modal, layout, err msgs

index.py
Sometimes the .lock file is release but not deleted from the disk.
Delete file manually at the end of routine process.
=> Improve routine lock.

requirements.txt
Added comment about installing pyadf from vendor directory.
=> Update requirements.txt with pyadf installation note
